import type { InsightSource, PlucoInsight } from './plucoInsights';

const polandRegisterBusiness: InsightSource = {
  title: { en: 'Registering a business in Poland', fa: 'ثبت کسب‌وکار در لهستان' },
  publisher: { en: 'Biznes.gov.pl — Polish Ministry of Economic Development and Technology', fa: 'Biznes.gov.pl — وزارت توسعه و فناوری لهستان' },
  url: 'https://biznes.gov.pl/en/firma/doing-business-in-poland/company-registration-in-poland',
};

const polandBeforeRegistering: InsightSource = {
  title: { en: 'What to know before registering a business', fa: 'نکات پیش از ثبت کسب‌وکار' },
  publisher: { en: 'Biznes.gov.pl — Polish Ministry of Economic Development and Technology', fa: 'Biznes.gov.pl — وزارت توسعه و فناوری لهستان' },
  url: 'https://biznes.gov.pl/en/portal/001823',
};

const yourEuropeStartingBusiness: InsightSource = {
  title: { en: 'Starting a business in the EU', fa: 'راه‌اندازی کسب‌وکار در اتحادیه اروپا' },
  publisher: { en: 'Your Europe — European Union', fa: 'Your Europe — اتحادیه اروپا' },
  url: 'https://europa.eu/youreurope/business/running-business/start-ups/starting-business/index_en.htm',
};

const euImmigrationPortal: InsightSource = {
  title: { en: 'EU Immigration Portal', fa: 'درگاه رسمی مهاجرت اتحادیه اروپا' },
  publisher: { en: 'European Commission', fa: 'کمیسیون اروپا' },
  url: 'https://home-affairs.ec.europa.eu/policies/migration-and-asylum/eu-immigration-portal_en',
};

const romeIRegulation: InsightSource = {
  title: { en: 'Rome I Regulation on the law applicable to contractual obligations', fa: 'مقررات رم یک درباره قانون حاکم بر تعهدات قراردادی' },
  publisher: { en: 'EUR-Lex — European Union law', fa: 'EUR-Lex — قوانین اتحادیه اروپا' },
  url: 'https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32008R0593',
};

const euCourtJurisdiction: InsightSource = {
  title: { en: 'Which EU country and court?', fa: 'کدام کشور و دادگاه اتحادیه اروپا؟' },
  publisher: { en: 'European e-Justice Portal', fa: 'درگاه عدالت الکترونیکی اروپا' },
  url: 'https://e-justice.europa.eu/topics/taking-legal-action/where-and-how/which-eu-country_en',
};

const euMediation: InsightSource = {
  title: { en: 'EU rules on mediation', fa: 'قواعد اتحادیه اروپا درباره میانجی‌گری' },
  publisher: { en: 'European e-Justice Portal', fa: 'درگاه عدالت الکترونیکی اروپا' },
  url: 'https://e-justice.europa.eu/topics/taking-legal-action/mediation/eu-rules-mediation_en',
};

const ebaComplaints: InsightSource = {
  title: { en: 'How to complain about a financial institution', fa: 'نحوه شکایت از یک مؤسسه مالی' },
  publisher: { en: 'European Banking Authority', fa: 'مرجع بانکی اروپا' },
  url: 'https://eba.europa.eu/activities/information-consumers/how-complain',
};

const usVisaSuspension: InsightSource = {
  title: { en: 'Suspension of visa issuance to foreign nationals', fa: 'تعلیق صدور ویزا برای اتباع کشورهای مشمول' },
  publisher: { en: 'U.S. Department of State', fa: 'وزارت امور خارجه ایالات متحده' },
  url: 'https://travel.state.gov/content/travel/en/News/visas-news/suspension-of-visa-issuance-to-foreign-nationals-to-protect-the-security-of-the-united-states.html',
};

const usIranImmigrantPost: InsightSource = {
  title: { en: 'Immigrant visa interview location policy', fa: 'سیاست محل مصاحبه ویزای مهاجرتی' },
  publisher: { en: 'U.S. Department of State', fa: 'وزارت امور خارجه ایالات متحده' },
  url: 'https://travel.state.gov/content/travel/en/News/visas-news/adjudicating-iv-applicants-in-their-country-of-residence.html',
};

const usNvc: InsightSource = {
  title: { en: 'National Visa Center and immigrant visa processing', fa: 'مرکز ملی ویزا و فرایند ویزای مهاجرتی' },
  publisher: { en: 'U.S. Department of State', fa: 'وزارت امور خارجه ایالات متحده' },
  url: 'https://travel.state.gov/content/travel/en/us-visas/immigrate/national-visa-center.html',
};

export const PLUCO_INSIGHTS_EXPANSION_B: Record<string, PlucoInsight> = {
  'poland-company-first-90-days-iranian-founder': {
    slug: 'poland-company-first-90-days-iranian-founder', category: { en: 'Poland Company', fa: 'شرکت در لهستان' }, country: { en: 'Poland', fa: 'لهستان' },
    title: { en: 'The First 90 Days of a Polish Company for an Iranian Founder', fa: '۹۰ روز نخست شرکت لهستانی برای بنیان‌گذار ایرانی' },
    description: { en: 'Move from company registration to a credible operating business through governance, tax, bookkeeping, banking, ownership and real commercial activity.', fa: 'از ثبت شرکت به کسب‌وکاری معتبر و عملیاتی برسید؛ با حاکمیت، مالیات، حسابداری، بانک، مالکیت و فعالیت تجاری واقعی.' },
    seoTitle: { en: 'Poland Company: First 90 Days for Iranian Founders', fa: '۹۰ روز نخست شرکت لهستانی برای ایرانیان' },
    seoDescription: { en: 'A 90-day operating plan for Iranian founders after Polish company registration: governance, beneficial ownership, tax, banking and real activity.', fa: 'برنامه ۹۰ روزه پس از ثبت شرکت لهستان؛ حاکمیت، مالک واقعی، مالیات، بانکداری و فعالیت عملیاتی.' },
    eyebrow: { en: 'FOUNDER OPERATIONS', fa: 'عملیات بنیان‌گذار' },
    introduction: { en: 'Registration creates a legal entity; it does not create customers, banking credibility, compliant records or residence rights. The first ninety days should convert the registry entry into an organisation that can explain what it does, who controls it and how money will move.', fa: 'ثبت، یک شخصیت حقوقی ایجاد می‌کند؛ نه مشتری، اعتبار بانکی، سوابق منطبق یا حق اقامت. نود روز نخست باید ورودی ثبت را به سازمانی تبدیل کند که بتواند توضیح دهد چه می‌کند، چه کسی آن را کنترل می‌کند و پول چگونه جریان خواهد یافت.' },
    image: '/images/insights/poland-company-first-90-days.webp', imageAlt: { en: 'Iranian founder and local adviser planning the first ninety days of a Polish company in Warsaw', fa: 'بنیان‌گذار ایرانی و مشاور محلی در حال برنامه‌ریزی نود روز نخست شرکت لهستانی در ورشو' },
    publishedOn: '2026-08-08', reviewedOn: '2026-08-08', readTime: { en: '9 minute read', fa: '۹ دقیقه مطالعه' },
    keywords: { en: ['Poland company Iranian founder first 90 days', 'operate Polish company after registration', 'Poland company bank tax bookkeeping', 'Iranian business Poland'], fa: ['ثبت شرکت لهستان برای ایرانیان', '۹۰ روز اول شرکت لهستان', 'بانک و مالیات شرکت لهستان', 'کسب‌وکار ایرانی در لهستان'] },
    sections: [
      { heading: { en: 'Days 1–30: establish control and mandatory records', fa: 'روزهای ۱ تا ۳۰؛ کنترل و سوابق الزامی را برقرار کنید' }, paragraphs: { en: ['Confirm the registered data, authorised representation, beneficial ownership filing, accounting engagement, tax responsibilities, e-delivery access and the calendar for every post-registration action. Official Polish guidance separates registration from supplementary notifications and ongoing obligations.', 'Create a controlled corporate archive containing the constitutional documents, registry evidence, resolutions, mandates, owner identification and professional appointments. A founder should always know who can sign, view official messages and move company funds.'], fa: ['اطلاعات ثبت‌شده، نمایندگی مجاز، ثبت ذی‌نفع واقعی، قرارداد حسابداری، مسئولیت‌های مالیاتی، دسترسی ابلاغ الکترونیکی و تقویم اقدامات پس از ثبت را تأیید کنید. راهنمای رسمی لهستان میان ثبت و اطلاع‌رسانی‌های تکمیلی و تعهدات جاری تفاوت می‌گذارد.', 'بایگانی کنترل‌شده شرکت شامل اساسنامه، مدارک ثبت، مصوبات، اختیارات، شناسایی مالکان و انتصاب متخصصان بسازید. بنیان‌گذار باید همیشه بداند چه کسی حق امضا، مشاهده پیام رسمی و جابه‌جایی پول شرکت را دارد.'] } },
      { heading: { en: 'Days 31–60: make banking and tax match the business', fa: 'روزهای ۳۱ تا ۶۰؛ بانک و مالیات را با کسب‌وکار هماهنگ کنید' }, paragraphs: { en: ['Prepare the business purpose, customer and supplier countries, expected transactions, source of capital and ownership structure before bank onboarding. Do not assume registration guarantees an account.', 'Choose bookkeeping and tax treatment around actual contracts and operations. VAT, payroll, social contributions, permits and sector rules depend on facts; a generic company package cannot decide them responsibly.'], fa: ['پیش از افتتاح حساب، هدف کسب‌وکار، کشورهای مشتری و تأمین‌کننده، تراکنش‌های مورد انتظار، منشأ سرمایه و ساختار مالکیت را آماده کنید. ثبت شرکت افتتاح حساب را تضمین نمی‌کند.', 'حسابداری و رفتار مالیاتی را بر اساس قراردادها و عملیات واقعی انتخاب کنید. مالیات بر ارزش افزوده، حقوق، حق بیمه، مجوز و قواعد صنفی به واقعیت‌ها وابسته‌اند؛ بسته عمومی شرکت نمی‌تواند مسئولانه درباره آن‌ها تصمیم بگیرد.'] } },
      { heading: { en: 'Days 61–90: demonstrate real commercial activity', fa: 'روزهای ۶۱ تا ۹۰؛ فعالیت تجاری واقعی را نشان دهید' }, paragraphs: { en: ['Align proposals, contracts, invoices, delivery evidence, website claims and account flows. The company should be able to explain where management decisions occur, who performs the work and why Poland is relevant to the operation.', 'Review the first quarter against the original plan. Correct dormant registrations, undocumented owner payments and unclear related-party transactions before they become a pattern. Registration is the beginning of governance, not its substitute.'], fa: ['پیشنهادها، قراردادها، فاکتورها، مدارک تحویل، ادعاهای وب‌سایت و جریان حساب را هماهنگ کنید. شرکت باید بتواند توضیح دهد تصمیم‌های مدیریتی کجا گرفته می‌شود، چه کسی کار را انجام می‌دهد و چرا لهستان برای عملیات اهمیت دارد.', 'سه‌ماهه نخست را با برنامه اولیه مقایسه کنید. ثبت‌های بلااستفاده، پرداخت‌های بدون مدرک مالک و تراکنش‌های مبهم اشخاص وابسته را پیش از تبدیل‌شدن به الگو اصلاح کنید. ثبت آغاز حاکمیت است، نه جایگزین آن.'] }, bullets: { en: ['Governance and signing authority', 'Beneficial ownership and filings', 'Accounting and tax calendar', 'Bank onboarding profile', 'Contracts and delivery evidence'], fa: ['حاکمیت و اختیار امضا', 'مالک واقعی و ثبت‌ها', 'تقویم حسابداری و مالیات', 'پروفایل افتتاح حساب', 'قرارداد و مدرک تحویل'] } },
    ],
    sources: [polandRegisterBusiness, polandBeforeRegistering],
    servicePath: { en: '/eu-company-registration', fa: '/fa/services/eu-company-registration' }, serviceLabel: { en: 'Plan a Polish company launch', fa: 'برنامه‌ریزی راه‌اندازی شرکت لهستانی' },
    relatedSlugs: ['eu-company-substance-management-residence', 'source-of-funds-story-european-bank', 'cross-border-contract-governing-law-jurisdiction'],
  },

  'eu-company-substance-management-residence': {
    slug: 'eu-company-substance-management-residence', category: { en: 'European Business', fa: 'کسب‌وکار اروپایی' }, country: { en: 'European Union', fa: 'اتحادیه اروپا' },
    title: { en: 'An EU Company Needs Operations, Management and Its Own Residence Analysis', fa: 'شرکت اروپایی به عملیات، مدیریت و تحلیل اقامت مستقل نیاز دارد' },
    description: { en: 'Why registration, operating substance, tax management, banking and the founder’s personal immigration position must be designed as connected but separate layers.', fa: 'چرا ثبت، عملیات واقعی، مدیریت مالیاتی، بانکداری و وضعیت مهاجرتی شخصی بنیان‌گذار باید مرتبط اما جدا طراحی شوند.' },
    seoTitle: { en: 'EU Company Substance, Management and Residence', fa: 'عملیات، مدیریت و اقامت در شرکت اروپایی' },
    seoDescription: { en: 'Separate EU company registration from operating substance, tax management, banking and the founder’s personal residence rights.', fa: 'ثبت شرکت اروپا را از عملیات واقعی، مدیریت مالیاتی، بانکداری و حق اقامت بنیان‌گذار تفکیک کنید.' },
    eyebrow: { en: 'BUSINESS ARCHITECTURE', fa: 'معماری کسب‌وکار' },
    introduction: { en: 'A certificate proves that a company exists. It does not prove where it is managed, what it sells, who performs the work, why its account activity makes sense or whether its owner may live and work in the same country. Those questions require separate evidence and sometimes separate advisers.', fa: 'گواهی ثبت ثابت می‌کند شرکت وجود دارد. اما نشان نمی‌دهد کجا مدیریت می‌شود، چه می‌فروشد، چه کسی کار را انجام می‌دهد، چرا فعالیت حساب منطقی است یا آیا مالک حق زندگی و کار در همان کشور را دارد. این پرسش‌ها به مدارک و گاهی مشاوران جدا نیاز دارند.' },
    image: '/images/insights/eu-company-substance-management.webp', imageAlt: { en: 'Iranian founder showing the real operations of a European design and technology studio to an adviser', fa: 'بنیان‌گذار ایرانی در حال نمایش عملیات واقعی استودیوی طراحی و فناوری اروپایی به مشاور' },
    publishedOn: '2026-08-08', reviewedOn: '2026-08-08', readTime: { en: '9 minute read', fa: '۹ دقیقه مطالعه' },
    keywords: { en: ['EU company substance requirements', 'company registration versus residence Europe', 'place of effective management EU company', 'Iranian founder European company'], fa: ['عملیات واقعی شرکت اروپایی', 'تفاوت ثبت شرکت و اقامت اروپا', 'مدیریت مؤثر شرکت اروپا', 'شرکت اروپایی برای بنیان‌گذار ایرانی'] },
    sections: [
      { heading: { en: 'A company should have an operational reason to exist', fa: 'شرکت باید دلیل عملیاتی برای وجود داشته باشد' }, paragraphs: { en: ['Define products, customers, suppliers, people, decision-making, assets and delivery. The selected jurisdiction should support that model rather than serve as a decorative address.', 'Evidence of substance is not a single rented desk. Contracts, staff or contractors, management records, bookkeeping, communications, premises where needed and actual delivery should form a consistent operating picture.'], fa: ['محصول، مشتری، تأمین‌کننده، افراد، تصمیم‌گیری، دارایی و تحویل را تعریف کنید. حوزه قضایی انتخابی باید از این مدل پشتیبانی کند، نه اینکه فقط نشانی تزئینی باشد.', 'مدرک عملیات واقعی یک میز اجاره‌ای نیست. قراردادها، کارکنان یا پیمانکاران، سوابق مدیریت، حسابداری، ارتباطات، محل لازم و تحویل واقعی باید تصویر عملیاتی منسجمی بسازند.'] } },
      { heading: { en: 'Management, tax and banking test different facts', fa: 'مدیریت، مالیات و بانک واقعیت‌های متفاوتی را می‌سنجند' }, paragraphs: { en: ['Corporate registration, tax residence, permanent establishment and personal tax residence are related concepts but not synonyms. Where key decisions are made and where work is performed can matter as much as the registered office.', 'Banking adds its own review of ownership, purpose, countries, counterparties and funds. Design the recordkeeping so the same legitimate business can be explained coherently to each institution.'], fa: ['ثبت شرکت، اقامت مالیاتی شرکت، مقر دائم و اقامت مالیاتی شخص مفاهیمی مرتبط اما متفاوت‌اند. محل تصمیم‌های کلیدی و انجام کار می‌تواند به‌اندازه نشانی ثبت‌شده اهمیت داشته باشد.', 'بانک نیز مالکیت، هدف، کشورها، طرف‌ها و وجوه را جداگانه بررسی می‌کند. ثبت سوابق را طوری طراحی کنید که همان کسب‌وکار قانونی برای هر مؤسسه به‌صورت منسجم قابل توضیح باشد.'] } },
      { heading: { en: 'The founder still needs a personal legal basis', fa: 'بنیان‌گذار همچنان به مبنای حقوقی شخصی نیاز دارد' }, paragraphs: { en: ['EU company ownership does not automatically give a non-EU founder permission to reside or work. The immigration route must be identified under the rules of the relevant country and matched to the founder’s actual role.', 'Build a four-layer plan: company law, tax, banking and personal immigration. Coordinate them, but never use one approval to imply that the other three are settled.'], fa: ['مالکیت شرکت اروپایی به‌طور خودکار به بنیان‌گذار خارج از اتحادیه اجازه اقامت یا کار نمی‌دهد. مسیر مهاجرتی باید بر اساس قواعد کشور مربوط و نقش واقعی فرد مشخص شود.', 'برنامه را در چهار لایه بسازید: حقوق شرکت، مالیات، بانکداری و مهاجرت شخصی. آن‌ها را هماهنگ کنید اما هیچ تأییدی را به معنای حل‌شدن سه لایه دیگر معرفی نکنید.'] } },
    ],
    sources: [yourEuropeStartingBusiness, euImmigrationPortal],
    servicePath: { en: '/eu-company-registration', fa: '/fa/services/eu-company-registration' }, serviceLabel: { en: 'Design a European company structure', fa: 'طراحی ساختار شرکت اروپایی' },
    relatedSlugs: ['poland-company-first-90-days-iranian-founder', 'eu-residency-route-map-iranian-family', 'european-bank-onboarding-iranian-client'],
  },

  'cross-border-contract-governing-law-jurisdiction': {
    slug: 'cross-border-contract-governing-law-jurisdiction', category: { en: 'International Contracts', fa: 'قراردادهای بین‌المللی' }, country: { en: 'Cross-Border', fa: 'فرامرزی' },
    title: { en: 'Governing Law Is Not Jurisdiction: Design the Cross-Border Contract Before the Dispute', fa: 'قانون حاکم همان صلاحیت دادگاه نیست؛ قرارداد فرامرزی را پیش از اختلاف طراحی کنید' },
    description: { en: 'A founder-focused guide to governing law, courts, arbitration, language, notices, delivery and evidence in international commercial agreements.', fa: 'راهنمایی برای قانون حاکم، دادگاه، داوری، زبان، ابلاغ، تحویل و مدارک در قراردادهای تجاری بین‌المللی.' },
    seoTitle: { en: 'Governing Law and Jurisdiction in Cross-Border Contracts', fa: 'قانون حاکم و صلاحیت در قرارداد بین‌المللی' },
    seoDescription: { en: 'Understand governing law, jurisdiction, arbitration, language, notices and evidence before signing an international commercial contract.', fa: 'قانون حاکم، صلاحیت، داوری، زبان، ابلاغ و مدارک را پیش از امضای قرارداد بین‌المللی روشن کنید.' },
    eyebrow: { en: 'CONTRACT DESIGN', fa: 'طراحی قرارداد' },
    introduction: { en: 'A contract can choose which law governs its obligations and still leave uncertainty about where a dispute will be heard. It can name a court yet remain unclear about language, service, evidence and whether a judgment can be used where the counterparty’s assets sit. These are design questions, not boilerplate.', fa: 'قرارداد می‌تواند قانون حاکم بر تعهدات را انتخاب کند و همچنان درباره محل رسیدگی اختلاف مبهم باشد. ممکن است دادگاهی را نام ببرد اما زبان، ابلاغ، مدارک و امکان استفاده از رأی در محل دارایی‌های طرف مقابل روشن نباشد. این‌ها پرسش‌های طراحی‌اند، نه متن‌های کلیشه‌ای.' },
    image: '/images/insights/cross-border-contract-law-jurisdiction.webp', imageAlt: { en: 'International founders and a legal adviser comparing governing law and jurisdiction for a cross-border contract', fa: 'بنیان‌گذاران بین‌المللی و مشاور حقوقی در حال مقایسه قانون حاکم و صلاحیت قرارداد فرامرزی' },
    publishedOn: '2026-08-08', reviewedOn: '2026-08-08', readTime: { en: '9 minute read', fa: '۹ دقیقه مطالعه' },
    keywords: { en: ['governing law versus jurisdiction contract', 'cross-border contract EU founder', 'international contract dispute clause', 'Rome I governing law'], fa: ['تفاوت قانون حاکم و صلاحیت دادگاه', 'قرارداد بین‌المللی کسب‌وکار', 'شرط حل اختلاف قرارداد خارجی', 'قانون حاکم قرارداد اروپا'] },
    sections: [
      { heading: { en: 'Separate law, forum and enforcement', fa: 'قانون، مرجع و اجرا را جدا ببینید' }, paragraphs: { en: ['The Rome I Regulation recognises party choice of law for contractual obligations within its scope. That choice does not itself select the court. Jurisdiction rules and any agreed court or arbitration clause require their own analysis.', 'Work backwards from assets and performance. Where are goods delivered, services performed, accounts held and counterparties established? A clause is valuable when it leads to a forum whose process and outcome can be used in the commercial reality.'], fa: ['مقررات رم یک در محدوده خود انتخاب قانون توسط طرفین را برای تعهدات قراردادی می‌پذیرد. این انتخاب به‌تنهایی دادگاه را مشخص نمی‌کند. قواعد صلاحیت و هر شرط دادگاه یا داوری به تحلیل مستقل نیاز دارد.', 'از دارایی‌ها و اجرا به عقب برگردید. کالا کجا تحویل می‌شود، خدمات کجا انجام می‌شود، حساب‌ها کجاست و طرف‌ها کجا مستقرند؟ شرط زمانی ارزشمند است که به مرجعی برسد که فرایند و نتیجه آن در واقعیت تجاری قابل استفاده باشد.'] } },
      { heading: { en: 'Turn the commercial deal into verifiable obligations', fa: 'توافق تجاری را به تعهدات قابل اثبات تبدیل کنید' }, paragraphs: { en: ['Define scope, specifications, acceptance, milestones, payment triggers, currency, tax treatment, intellectual property, confidentiality, change control and termination in language the operating teams can follow.', 'Name authorised contacts and notice methods. Preserve signed versions, changes, approvals and delivery evidence in one system. A beautifully drafted clause cannot replace proof that the parties performed or failed to perform.'], fa: ['دامنه، مشخصات، پذیرش، مراحل، محرک پرداخت، ارز، رفتار مالیاتی، مالکیت فکری، محرمانگی، کنترل تغییر و خاتمه را به زبانی تعریف کنید که تیم اجرایی بتواند دنبال کند.', 'افراد مجاز و روش ابلاغ را نام ببرید. نسخه‌های امضا‌شده، تغییرات، تأییدها و مدارک تحویل را در یک سیستم نگه دارید. شرط زیبا جای مدرک انجام یا عدم انجام تعهد را نمی‌گیرد.'] } },
      { heading: { en: 'Resolve language and authority before signature', fa: 'زبان و اختیار را پیش از امضا حل کنید' }, paragraphs: { en: ['For bilingual agreements, specify which version controls and test whether both versions carry the same commercial effect. Confirm the legal identity and signing authority of every party instead of relying on email signatures or brand names.', 'Review sanctions, payment routes and regulated-sector requirements separately. Contract freedom does not override mandatory rules. The objective is a document that the business can operate and a dispute team can understand years later.'], fa: ['در قرارداد دوزبانه مشخص کنید کدام نسخه حاکم است و بررسی کنید هر دو نسخه اثر تجاری یکسان دارند. هویت حقوقی و اختیار امضای هر طرف را تأیید کنید و به امضای ایمیل یا نام برند اکتفا نکنید.', 'تحریم‌ها، مسیر پرداخت و الزامات بخش‌های تحت نظارت را جداگانه بررسی کنید. آزادی قراردادی قواعد آمره را کنار نمی‌زند. هدف سندی است که کسب‌وکار بتواند اجرا کند و تیم اختلاف سال‌ها بعد بفهمد.'] }, bullets: { en: ['Chosen law', 'Court or arbitration forum', 'Controlling language', 'Notice and signature authority', 'Delivery and acceptance evidence'], fa: ['قانون منتخب', 'دادگاه یا مرجع داوری', 'زبان حاکم', 'ابلاغ و اختیار امضا', 'مدرک تحویل و پذیرش'] } },
    ],
    sources: [romeIRegulation, euCourtJurisdiction],
    servicePath: { en: '/international-contracts', fa: '/fa/services/international-contracts' }, serviceLabel: { en: 'Review an international contract', fa: 'بازبینی قرارداد بین‌المللی' },
    relatedSlugs: ['cross-border-dispute-evidence-first-72-hours', 'international-dispute-mediation-litigation-strategy', 'spain-digital-nomad-contract-audit'],
  },

  'cross-border-dispute-evidence-first-72-hours': {
    slug: 'cross-border-dispute-evidence-first-72-hours', category: { en: 'Dispute Resolution', fa: 'حل اختلاف' }, country: { en: 'Cross-Border', fa: 'فرامرزی' },
    title: { en: 'The First 72 Hours of a Cross-Border Dispute: Preserve Before You Perform', fa: '۷۲ ساعت نخست اختلاف فرامرزی؛ پیش از واکنش، مدارک را حفظ کنید' },
    description: { en: 'A calm evidence-first protocol for contracts, messages, payments, deliveries, systems and decision authority when an international dispute emerges.', fa: 'پروتکل آرام و مبتنی بر مدرک برای قرارداد، پیام، پرداخت، تحویل، سامانه و اختیار تصمیم هنگام شکل‌گیری اختلاف بین‌المللی.' },
    seoTitle: { en: 'First 72 Hours of a Cross-Border Business Dispute', fa: '۷۲ ساعت نخست اختلاف تجاری بین‌المللی' },
    seoDescription: { en: 'Preserve contracts, messages, payments, delivery evidence and systems before responding to a cross-border commercial dispute.', fa: 'پیش از پاسخ به اختلاف فرامرزی، قرارداد، پیام، پرداخت، مدارک تحویل و سامانه‌ها را حفظ کنید.' },
    eyebrow: { en: 'EVIDENCE FIRST', fa: 'ابتدا مدارک' },
    introduction: { en: 'The first instinct in a dispute is often to send a forceful message. The better first move is usually quieter: stop deletion, identify the contract and forum, preserve originals, secure access and decide who is authorised to communicate. A careless response can create a new problem before the original one is understood.', fa: 'نخستین غریزه در اختلاف اغلب ارسال پیامی تند است. حرکت بهتر معمولاً آرام‌تر است: حذف را متوقف کنید، قرارداد و مرجع را بیابید، اصل مدارک را حفظ کنید، دسترسی را امن سازید و مشخص کنید چه کسی مجاز به ارتباط است. پاسخ بی‌دقت می‌تواند پیش از فهم مشکل اصلی، مسئله تازه‌ای بسازد.' },
    image: '/images/insights/cross-border-dispute-evidence.webp', imageAlt: { en: 'Iranian business owner and adviser preserving digital and paper evidence after a cross-border dispute', fa: 'صاحب کسب‌وکار ایرانی و مشاور در حال حفظ مدارک دیجیتال و کاغذی پس از اختلاف فرامرزی' },
    publishedOn: '2026-08-08', reviewedOn: '2026-08-08', readTime: { en: '8 minute read', fa: '۸ دقیقه مطالعه' },
    keywords: { en: ['cross-border dispute evidence preservation', 'international contract dispute first steps', 'business dispute document hold', 'commercial dispute chronology'], fa: ['حفظ مدارک اختلاف بین‌المللی', 'اقدامات نخست اختلاف تجاری', 'مدارک دعوای قراردادی', 'گاه‌شمار اختلاف فرامرزی'] },
    sections: [
      { heading: { en: 'Hour 0–12: preserve systems and originals', fa: 'ساعت ۰ تا ۱۲؛ سامانه‌ها و اصل مدارک را حفظ کنید' }, paragraphs: { en: ['Suspend routine deletion for relevant email, messaging, shared drives, accounting, delivery and device data. Preserve original files with metadata where possible rather than relying only on screenshots or forwarded copies.', 'Identify access risk. Change compromised credentials through authorised channels, record who has custody of devices and do not alter disputed documents. Preservation should be proportionate and privacy-aware.'], fa: ['حذف عادی ایمیل، پیام‌رسان، فضای اشتراکی، حسابداری، تحویل و داده دستگاه‌های مرتبط را متوقف کنید. در صورت امکان فایل اصلی را با فراداده حفظ کنید و فقط به اسکرین‌شات یا نسخه فورواردشده اکتفا نکنید.', 'ریسک دسترسی را مشخص کنید. اعتبارنامه در معرض خطر را از مسیر مجاز تغییر دهید، تحویل‌گیرنده دستگاه‌ها را ثبت کنید و اسناد مورد اختلاف را دستکاری نکنید. حفظ مدارک باید متناسب و همراه با رعایت حریم خصوصی باشد.'] } },
      { heading: { en: 'Hour 12–36: build facts before arguments', fa: 'ساعت ۱۲ تا ۳۶؛ پیش از استدلال، واقعیت‌ها را بسازید' }, paragraphs: { en: ['Locate the signed contract, amendments, governing law, forum, notices, milestones and termination provisions. Build a neutral chronology linking each material event to its evidence.', 'Separate known facts, assumptions and unanswered questions. Reconcile invoices, payments, deliveries, acceptance records and communications. The first internal report should be accurate enough to support a decision, not persuasive enough to win an argument.'], fa: ['قرارداد امضا‌شده، اصلاحات، قانون حاکم، مرجع، ابلاغ‌ها، مراحل و شروط خاتمه را پیدا کنید. گاه‌شمار خنثی بسازید که هر رویداد مهم را به مدرک آن متصل کند.', 'واقعیت‌های قطعی، فرض‌ها و پرسش‌های بی‌پاسخ را جدا کنید. فاکتور، پرداخت، تحویل، پذیرش و ارتباطات را تطبیق دهید. گزارش داخلی نخست باید برای تصمیم‌گیری دقیق باشد، نه برای پیروزی در بحث متقاعدکننده.'] } },
      { heading: { en: 'Hour 36–72: choose a controlled response', fa: 'ساعت ۳۶ تا ۷۲؛ پاسخ کنترل‌شده انتخاب کنید' }, paragraphs: { en: ['Decide who can speak for the organisation and what immediate objective matters: preserving rights, stopping harm, obtaining information, continuing performance or opening settlement discussion. Check contractual notice requirements before sending.', 'Avoid admissions, threats or public accusations made without analysis. The appropriate response may be a reservation-of-rights letter, operational cure proposal, evidence request, complaint or confidential settlement approach depending on the forum and facts.'], fa: ['مشخص کنید چه کسی از طرف سازمان سخن می‌گوید و هدف فوری چیست: حفظ حقوق، توقف زیان، دریافت اطلاعات، ادامه اجرا یا آغاز مذاکره. پیش از ارسال، شرایط ابلاغ قراردادی را بررسی کنید.', 'از اقرار، تهدید یا اتهام عمومی بدون تحلیل پرهیز کنید. بر اساس مرجع و واقعیت، پاسخ می‌تواند نامه حفظ حقوق، پیشنهاد اصلاح عملیاتی، درخواست مدرک، شکایت یا رویکرد محرمانه سازش باشد.'] }, bullets: { en: ['Preservation notice', 'Original contract set', 'Neutral chronology', 'Loss and payment map', 'Single authorised communicator'], fa: ['دستور حفظ مدارک', 'مجموعه اصل قرارداد', 'گاه‌شمار خنثی', 'نقشه زیان و پرداخت', 'یک فرد مجاز برای ارتباط'] } },
    ],
    sources: [euCourtJurisdiction, ebaComplaints],
    servicePath: { en: '/dispute-resolution', fa: '/fa/services/dispute-resolution' }, serviceLabel: { en: 'Assess a cross-border dispute', fa: 'ارزیابی اختلاف فرامرزی' },
    relatedSlugs: ['international-dispute-mediation-litigation-strategy', 'cross-border-contract-governing-law-jurisdiction', 'european-bank-onboarding-iranian-client'],
  },

  'international-dispute-mediation-litigation-strategy': {
    slug: 'international-dispute-mediation-litigation-strategy', category: { en: 'Dispute Resolution', fa: 'حل اختلاف' }, country: { en: 'European Union', fa: 'اتحادیه اروپا' },
    title: { en: 'Negotiate, Mediate or Litigate? Match the Process to the Cross-Border Outcome', fa: 'مذاکره، میانجی‌گری یا دادگاه؟ فرایند را با نتیجه فرامرزی هماهنگ کنید' },
    description: { en: 'Compare negotiation, mediation and proceedings by urgency, evidence, confidentiality, enforceability, relationship and the location of assets.', fa: 'مذاکره، میانجی‌گری و رسیدگی را بر اساس فوریت، مدرک، محرمانگی، قابلیت اجرا، رابطه و محل دارایی مقایسه کنید.' },
    seoTitle: { en: 'Mediation or Litigation for Cross-Border Disputes', fa: 'میانجی‌گری یا دادگاه در اختلاف فرامرزی' },
    seoDescription: { en: 'Choose negotiation, mediation or litigation for an international dispute using urgency, evidence, cost, confidentiality and enforceability.', fa: 'برای اختلاف بین‌المللی با توجه به فوریت، مدرک، هزینه، محرمانگی و قابلیت اجرا فرایند مناسب را انتخاب کنید.' },
    eyebrow: { en: 'DISPUTE STRATEGY', fa: 'راهبرد اختلاف' },
    introduction: { en: 'The most aggressive process is not always the strongest. A private client may need an urgent order, a commercial reset, a confidential payment plan, an enforceable judgment or simply enough verified information to decide. Process should be selected around that outcome.', fa: 'تهاجمی‌ترین فرایند همیشه قوی‌ترین نیست. موکل خصوصی ممکن است به دستور فوری، بازتنظیم تجاری، برنامه پرداخت محرمانه، رأی قابل اجرا یا فقط اطلاعات تأییدشده برای تصمیم نیاز داشته باشد. فرایند باید حول نتیجه انتخاب شود.' },
    image: '/images/insights/international-dispute-mediation.webp', imageAlt: { en: 'Iranian and European business principals in a confidential cross-border mediation with a neutral mediator', fa: 'طرف‌های تجاری ایرانی و اروپایی در میانجی‌گری محرمانه فرامرزی با میانجی بی‌طرف' },
    publishedOn: '2026-08-08', reviewedOn: '2026-08-08', readTime: { en: '8 minute read', fa: '۸ دقیقه مطالعه' },
    keywords: { en: ['mediation versus litigation international dispute', 'cross-border commercial mediation EU', 'international dispute strategy', 'settle European business dispute'], fa: ['میانجی‌گری یا دادگاه اختلاف بین‌المللی', 'میانجی‌گری تجاری اروپا', 'راهبرد حل اختلاف فرامرزی', 'سازش اختلاف کسب‌وکار'] },
    sections: [
      { heading: { en: 'Define the outcome and the constraints', fa: 'نتیجه و محدودیت‌ها را تعریف کنید' }, paragraphs: { en: ['List the commercial result, urgent risks, evidence strength, cash position, relationship value, confidentiality need and assets available for enforcement. Different outcomes can justify different processes or a deliberate sequence.', 'A claim may be legally sound but commercially poor if enforcement is remote, management time is disproportionate or publicity damages a valuable relationship. The opposite can also be true when delay allows assets or evidence to disappear.'], fa: ['نتیجه تجاری، ریسک فوری، قدرت مدارک، وضعیت نقدی، ارزش رابطه، نیاز به محرمانگی و دارایی قابل اجرا را فهرست کنید. نتایج متفاوت می‌تواند فرایندهای متفاوت یا ترتیب آگاهانه‌ای از آن‌ها را توجیه کند.', 'ممکن است ادعا از نظر حقوقی قوی اما از نظر تجاری ضعیف باشد اگر اجرا دور، زمان مدیریت نامتناسب یا علنی‌شدن برای رابطه ارزشمند زیان‌بار باشد. عکس آن نیز زمانی ممکن است که تأخیر باعث ناپدیدشدن دارایی یا مدرک شود.'] } },
      { heading: { en: 'Use mediation for controlled commercial space', fa: 'از میانجی‌گری برای فضای تجاری کنترل‌شده استفاده کنید' }, paragraphs: { en: ['EU rules encourage mediation in cross-border civil and commercial disputes. Mediation can create room for payment timing, revised delivery, confidentiality, future business and solutions a court may not order.', 'It still requires preparation. Know the facts, authority, realistic alternatives and terms needed for an enforceable settlement. Confidentiality should be defined under the applicable framework, not assumed from the room.'], fa: ['قواعد اتحادیه اروپا میانجی‌گری را در اختلاف‌های مدنی و تجاری فرامرزی تشویق می‌کند. میانجی‌گری می‌تواند برای زمان‌بندی پرداخت، تحویل اصلاح‌شده، محرمانگی، همکاری آینده و راه‌حل‌هایی که دادگاه صادر نمی‌کند فضا بسازد.', 'میانجی‌گری نیز به آمادگی نیاز دارد. واقعیت‌ها، اختیار، جایگزین‌های واقعی و شرایط لازم برای سازش قابل اجرا را بدانید. محرمانگی باید بر اساس چارچوب مربوط تعریف شود، نه اینکه صرفاً از جلسه فرض شود.'] } },
      { heading: { en: 'Preserve formal options while exploring settlement', fa: 'هم‌زمان با سازش، گزینه‌های رسمی را حفظ کنید' }, paragraphs: { en: ['Limitation periods, notice clauses, interim relief and forum rules can continue to matter during negotiation. A settlement discussion should not accidentally surrender rights or create a misleading record.', 'The strategy may combine a precise formal notice, evidence preservation and a time-limited mediation window. If proceedings become necessary, the earlier discipline reduces cost and improves clarity.'], fa: ['مرور زمان، شروط ابلاغ، دستور موقت و قواعد مرجع در زمان مذاکره نیز مهم‌اند. گفت‌وگوی سازش نباید ناخواسته حقی را از بین ببرد یا سابقه گمراه‌کننده بسازد.', 'راهبرد می‌تواند اخطار رسمی دقیق، حفظ مدارک و پنجره زمانی محدود برای میانجی‌گری را ترکیب کند. اگر رسیدگی لازم شود، انضباط اولیه هزینه را کاهش و وضوح را افزایش می‌دهد.'] } },
    ],
    sources: [euMediation, euCourtJurisdiction],
    servicePath: { en: '/dispute-resolution', fa: '/fa/services/dispute-resolution' }, serviceLabel: { en: 'Design a dispute strategy', fa: 'طراحی راهبرد حل اختلاف' },
    relatedSlugs: ['cross-border-dispute-evidence-first-72-hours', 'cross-border-contract-governing-law-jurisdiction', 'source-of-funds-story-european-bank'],
  },

  'us-green-card-iranian-families-2026': {
    slug: 'us-green-card-iranian-families-2026', category: { en: 'Current U.S. Policy', fa: 'سیاست جاری آمریکا' }, country: { en: 'United States', fa: 'ایالات متحده' },
    title: { en: 'U.S. Green Card Planning for Iranian Families in 2026: Status Before Strategy', fa: 'برنامه گرین‌کارت برای خانواده ایرانی در ۲۰۲۶؛ ابتدا وضعیت، سپس راهبرد' },
    description: { en: 'A current, source-led briefing on the 2026 U.S. visa-issuance suspension for Iranian nationals, limited exceptions, case posture and why old pathway articles are unsafe.', fa: 'گزارش مستند درباره تعلیق صدور ویزای آمریکا برای اتباع ایرانی در ۲۰۲۶، استثناهای محدود، وضعیت پرونده و خطر اتکا به مقالات قدیمی.' },
    seoTitle: { en: 'U.S. Green Card for Iranians in 2026: Current Rules', fa: 'گرین‌کارت آمریکا برای ایرانیان در ۲۰۲۶؛ وضعیت جاری' },
    seoDescription: { en: 'Current 2026 guidance on U.S. visa issuance for Iranian nationals, limited exceptions, pending cases and immigrant-visa planning.', fa: 'راهنمای جاری ۲۰۲۶ درباره صدور ویزای آمریکا برای ایرانیان، استثناهای محدود و برنامه‌ریزی پرونده مهاجرتی.' },
    eyebrow: { en: 'POLICY STATUS BRIEFING', fa: 'گزارش وضعیت سیاست' },
    introduction: { en: 'A Green Card category and the ability to receive an immigrant visa are not the same question. As of this article’s review date, the U.S. Department of State states that visa issuance is fully suspended for Iranian nationals across immigrant and nonimmigrant categories, subject to limited exceptions. Any responsible plan must begin with that current restriction, not with an older description of family, employment or diversity pathways.', fa: 'داشتن یک گروه قانونی گرین‌کارت و امکان دریافت ویزای مهاجرتی یک پرسش نیست. در تاریخ بازبینی این مقاله، وزارت امور خارجه آمریکا اعلام می‌کند صدور ویزا برای اتباع ایرانی در گروه‌های مهاجرتی و غیرمهاجرتی، با استثناهای محدود، به‌طور کامل تعلیق است. هر برنامه مسئولانه باید از این محدودیت جاری آغاز شود، نه از توضیح قدیمی مسیر خانوادگی، کاری یا لاتاری.' },
    image: '/images/insights/us-green-card-iranian-families-2026.webp', imageAlt: { en: 'Iranian family reviewing the uncertain 2026 United States immigrant visa position with a private adviser', fa: 'خانواده ایرانی در حال بررسی وضعیت نامطمئن ویزای مهاجرتی آمریکا در ۲۰۲۶ با مشاور خصوصی' },
    publishedOn: '2026-08-08', reviewedOn: '2026-08-08', readTime: { en: '9 minute read', fa: '۹ دقیقه مطالعه' },
    keywords: { en: ['US Green Card Iranian 2026 visa suspension', 'Iranian immigrant visa current rules', 'Green Card Iran exceptions 2026', 'US immigrant visa Iranian family'], fa: ['گرین کارت آمریکا برای ایرانیان ۲۰۲۶', 'تعلیق ویزای آمریکا برای ایرانیان', 'استثناهای ویزای مهاجرتی ایران', 'وضعیت مهاجرت آمریکا ایرانیان'] },
    sections: [
      { heading: { en: 'The current suspension changes the practical question', fa: 'تعلیق جاری پرسش عملی را تغییر می‌دهد' }, paragraphs: { en: ['The State Department notice says that, effective 1 January 2026, visa issuance is fully suspended for nationals of Iran and other listed countries, with limited categorical exceptions. It also states that earlier broad immediate-family exceptions are no longer available under the current proclamation.', 'The listed exceptions include certain diplomatic or official visas, immigrant visas for ethnic and religious minorities facing persecution in Iran, dual nationals applying with a passport of a nationality not subject to suspension, certain U.S.-government employee special immigrant visas and specified major sporting participants. A case-specific waiver may exist under the governing proclamation, but it is discretionary and should never be marketed as predictable.'], fa: ['اطلاعیه وزارت امور خارجه می‌گوید از ۱ ژانویه ۲۰۲۶ صدور ویزا برای اتباع ایران و دیگر کشورهای فهرست‌شده، با استثناهای محدود، به‌طور کامل تعلیق است. همچنین بیان می‌کند استثناهای گسترده پیشین برای بستگان نزدیک در اعلامیه جاری دیگر وجود ندارد.', 'استثناهای فهرست‌شده شامل برخی ویزاهای دیپلماتیک یا رسمی، ویزای مهاجرتی اقلیت‌های قومی و مذهبی تحت آزار در ایران، دارندگان تابعیت دوگانه که با گذرنامه تابعیت غیرمشمول درخواست می‌کنند، برخی ویزاهای ویژه کارکنان دولت آمریکا و شرکت‌کنندگان مشخص رویدادهای ورزشی است. معافیت موردی ممکن است در چارچوب اعلامیه وجود داشته باشد، اما اختیاری است و نباید قابل پیش‌بینی معرفی شود.'] } },
      { heading: { en: 'Separate category, petition, visa and entry', fa: 'گروه، دادخواست، ویزا و ورود را تفکیک کنید' }, paragraphs: { en: ['A family or employment petition may establish a relationship or classification, while the National Visa Center manages document processing after an approved petition in many consular cases. Visa availability, admissibility, interview operations and the current suspension remain separate layers.', 'Before spending further time or money, identify nationality and passports, current residence, existing U.S. status or visa, petition stage, priority date, processing post and any possible exception. Do not assume that petition approval overcomes visa-issuance or entry restrictions.'], fa: ['دادخواست خانوادگی یا کاری ممکن است رابطه یا گروه را ثابت کند و مرکز ملی ویزا در بسیاری از پرونده‌های کنسولی پس از تأیید دادخواست، مدارک را پردازش می‌کند. موجودبودن شماره ویزا، قابلیت پذیرش، عملیات مصاحبه و تعلیق جاری لایه‌های جدا هستند.', 'پیش از صرف زمان یا هزینه بیشتر، ملیت و گذرنامه‌ها، محل اقامت فعلی، وضعیت یا ویزای موجود آمریکا، مرحله دادخواست، تاریخ اولویت، پست پردازش و هر استثنای احتمالی را مشخص کنید. تأیید دادخواست را به معنای غلبه بر محدودیت صدور ویزا یا ورود ندانید.'] } },
      { heading: { en: 'Protect pending cases without promising an outcome', fa: 'از پرونده‌های در جریان بدون وعده نتیجه محافظت کنید' }, paragraphs: { en: ['Keep official notices, deadlines, civil documents and NVC communications current. The Department of State says immigrant visa applicants are generally scheduled in the designated district for their residence or, if requested, nationality, with limited exceptions; residents of countries without routine visa operations use designated processing posts.', 'Policy can change quickly. Recheck the State Department and relevant post immediately before any filing, transfer, interview or travel decision. This article does not establish eligibility or an exception, and PLUCO GROUP does not guarantee U.S. visa issuance, admission or waiver approval.'], fa: ['اطلاعیه‌های رسمی، مهلت‌ها، مدارک مدنی و ارتباطات NVC را به‌روز نگه دارید. وزارت امور خارجه می‌گوید متقاضی ویزای مهاجرتی معمولاً در حوزه تعیین‌شده محل اقامت یا در صورت درخواست، تابعیت برنامه‌ریزی می‌شود و استثناها محدودند؛ ساکنان کشورهایی بدون عملیات عادی ویزا از پست‌های تعیین‌شده استفاده می‌کنند.', 'سیاست می‌تواند سریع تغییر کند. پیش از هر درخواست، انتقال، مصاحبه یا تصمیم سفر، منابع وزارت امور خارجه و پست مربوط را دوباره بررسی کنید. این مقاله صلاحیت یا استثنا را ثابت نمی‌کند و PLUCO GROUP صدور ویزای آمریکا، ورود یا تأیید معافیت را تضمین نمی‌کند.'] }, bullets: { en: ['Current nationality and all passports', 'Existing visa or U.S. status', 'Petition and priority-date posture', 'Designated interview post', 'Exception or waiver analysis from current rules'], fa: ['ملیت فعلی و همه گذرنامه‌ها', 'ویزای موجود یا وضعیت آمریکا', 'مرحله دادخواست و تاریخ اولویت', 'پست تعیین‌شده مصاحبه', 'تحلیل استثنا یا معافیت بر اساس قواعد جاری'] } },
    ],
    sources: [usVisaSuspension, usIranImmigrantPost, usNvc],
    servicePath: { en: '/us-green-card', fa: '/us-green-card' }, serviceLabel: { en: 'Request a current U.S. policy assessment', fa: 'درخواست ارزیابی وضعیت جاری آمریکا' },
    relatedSlugs: ['eu-residency-route-map-iranian-family', 'source-of-funds-story-european-bank', 'first-year-spain-family-life-plan'],
  },
};
