export const seoConfig = {
  siteName: 'PLUCO GROUP',
  canonicalOrigin: 'https://www.plucogroup.com',
  locales: ['en', 'fa'],
  requiredPublicPaths: [
    '/',
    '/guides',
    '/editorial-standards',
    '/resources/source-of-funds-checklist',
    '/fa',
    '/fa/guides',
    '/fa/editorial-standards',
    '/fa/resources/source-of-funds-checklist',
  ],
  privatePathPrefixes: [
    '/api/',
    '/admin/',
    '/agent/',
    '/dashboard/',
    '/consultant/',
    '/compliance-officer/',
    '/case-manager/',
    '/document-reviewer/',
    '/enquiry-handler/',
    '/customer-service/',
    '/bookings/',
    '/help/',
    '/login',
    '/signup',
    '/complete-login',
    '/forgot-password',
    '/reset-password',
    '/verify-email',
    '/verify-otp',
    '/client-sign-in',
  ],
  topicClusters: [
    {
      name: 'European residency',
      primaryIntent: 'European residency planning for international families and entrepreneurs',
      servicePaths: ['/eu-residency', '/spain-digital-nomad-visa'],
      guidePaths: ['/guides/choose-eu-residency-route', '/guides/spain-digital-nomad-document-checklist'],
    },
    {
      name: 'Banking and source of funds',
      primaryIntent: 'European banking compliance and source-of-funds support for international clients',
      servicePaths: ['/banking', '/banking-compliance', '/financial-discrimination'],
      guidePaths: [
        '/guides/bank-account-closure-iranian-nationals-europe',
        '/guides/eu-bank-account-opening-iranian-nationals',
        '/guides/source-of-funds-file',
        '/resources/source-of-funds-checklist',
      ],
    },
    {
      name: 'European company formation',
      primaryIntent: 'EU and Poland company formation for international founders',
      servicePaths: ['/eu-company-registration', '/business-solutions'],
      guidePaths: ['/guides/eu-company-versus-residency', '/guides/poland-company-registration-iranian-founders'],
    },
    {
      name: 'Cross-border property',
      primaryIntent: 'European property purchase planning for international buyers',
      servicePaths: ['/eu-property-purchase'],
      guidePaths: ['/guides/spain-property-purchase-iranian-buyers'],
    },
    {
      name: 'International mobility planning',
      primaryIntent: 'Neutral mobility, nationality, family and compliance planning',
      servicePaths: ['/new-identity', '/us-green-card'],
      guidePaths: [],
    },
    {
      name: 'Cross-border legal protection',
      primaryIntent: 'International contracts and cross-border dispute strategy',
      servicePaths: ['/international-contracts', '/dispute-resolution'],
      guidePaths: [],
    },
  ],
};
